version: '3.7'

services:
  apache:
    build: .
    restart: always
    ports:
      - 80:80
      - 443:443
  mariadb:
    image: mariadb:10.4
    restart: always
    ports:
      - 3306:3306
    env_file: .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    restart: always
    ports:
      - 8080:80
    env_file: .env
    environment:
      PMA_HOST: mariadb